# Generated by Django 5.2 on 2025-04-26 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_workflow', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditanalysis',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditpaper',
            name='compiled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditquestionnaire',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='assigned_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='business_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_sponsored_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_workflow.counterparty'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_requests', to='credit_workflow.counterparty'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='second_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_sponsored_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='workflow_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowstate'),
        ),
        migrations.AddField(
            model_name='creditquestionnaire',
            name='credit_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='creditpaper',
            name='credit_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_paper', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='credit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='creditanalysis',
            name='credit_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_analysis', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='credit_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_documents', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='credit_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_review', to='credit_workflow.creditrequest'),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditlimit',
            name='limit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_workflow.limittype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'type')},
        ),
    ]
