# Generated by Django 5.2 on 2025-05-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_workflow', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalreview',
            name='counterparty_default_events',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='counterparty_termination_events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='credit_support_annex',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='csa_additional_provisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='csa_independent_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='csa_minimum_transfer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='csa_threshold',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='csa_type',
            field=models.CharField(blank=True, choices=[('one_way', 'One-way'), ('two_way', 'Two-way'), ('none', 'None')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='governing_law',
            field=models.CharField(choices=[('english', 'English'), ('new_york', 'New York'), ('other', 'Other')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='grace_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='iosco_compliant',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='isda_master_agreement',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('pending', 'Pending')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='material_provisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='positive_collateral_opinion',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='legalreview',
            name='positive_netting_opinion',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not Applicable')], default='no', max_length=20),
        ),
    ]
