# Generated by Django 5.2 on 2025-04-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_draft_state', models.BooleanField(default=False)),
                ('parent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_states', to='workflow.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_id', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('required_roles', models.CharField(help_text='Comma-separated list of required role IDs (see PRD)', max_length=128)),
                ('actions_required', models.TextField(blank=True)),
                ('is_draft_action', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.workflowstate')),
            ],
        ),
    ]
